name: Update Contributions Badge

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update badge
        run: |
          # Fetch contribution count from GitHub API
          COUNT=$(curl -s "https://api.github.com/users/LiamSwayne" | grep -o '"contributions": [0-9]*' | awk '{print $2}')

          # Generate badge SVG using Shields.io
          BADGE_URL="https://img.shields.io/badge/Contributions-$COUNT-blue.svg"
          curl -s -o contributions_badge.svg "$BADGE_URL"

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add contributions_badge.svg
          git commit -m "Update contributions badge [skip ci]"
          git push
