name: Remove completed content from subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Archive URLs
      run: |
        archival_urls=(
          "https://flixpatrol.com/top10/amazon-prime/united-states/"
          "https://flixpatrol.com/top10/amazon-prime/"
          "https://flixpatrol.com/top10/"
          "https://flixpatrol.com/top10/netflix/united-states/"
          "https://flixpatrol.com/top10/netflix/"
          "https://flixpatrol.com/top10/hulu/united-states/"
          "https://flixpatrol.com/top10/hulu/"
          "https://flixpatrol.com/top10/paramount-plus/united-states/"
          "https://flixpatrol.com/top10/paramount-plus/"
          "https://flixpatrol.com/top10/disney/"
          "https://flixpatrol.com/top10/disney/united-states/"
          "https://flixpatrol.com/top10/apple-tv/"
          "https://flixpatrol.com/top10/apple-tv/united-states/"
          "https://flixpatrol.com/top10/amazon-prime/united-kingdom/"
          "https://flixpatrol.com/top10/netflix/united-kingdom/"
          "https://flixpatrol.com/top10/hulu/united-kingdom/"
          "https://flixpatrol.com/top10/paramount-plus/united-kingdom/"
          "https://flixpatrol.com/top10/disney/united-kingdom/"
          "https://flixpatrol.com/top10/apple-tv/united-kingdom/"
        )

        for url in "${archival_urls[@]}"; do
          # Retry loop for the main content
          max_retries=3
          retry_counter=0
          while [ $retry_counter -lt $max_retries ]; do
            if curl -sS "https://web.archive.org/save/$url" > /dev/null; then
              break
            else
              ((retry_counter++))
              echo "Failed to archive main page: $url. Retrying..."
            fi
          done || true

          # Retry loop for outlinks
          curl -sS "$url" | grep -oP 'href="\K[^"]+' | while read -r outlink; do
            max_retries=3
            retry_counter=0
            while [ $retry_counter -lt $max_retries ]; do
              if curl -sS "https://web.archive.org/save/$outlink" > /dev/null; then
                break
              else
                ((retry_counter++))
                echo "Failed to archive outlink: $outlink. Retrying..."
              fi
            done || true
          done
        done
