name: Display Contribution Count

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git
      uses: actions/checkout@v2
      
    - name: Display Contribution Count
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        contribution_count=$(curl -s "https://api.github.com/users/${GITHUB_ACTOR}" | jq -r .contributions)
        echo "My total contribution count: ${contribution_count}" > README.md
        git add README.md
        git commit -m "Update README with contribution count"
        git push
